### ISSUE TITLE
Replace custom encoding/decoding implementation

### ISSUE THREAD

**Issue by pizzafox** [vysiondev/lolihost#1]
https://github.com/vysiondev/lolihost/blob/db8e6389cb294c19bbc2a8b070d366dec15f93b3/zws.go#L53

This is a mistake I originally made when creating ZWS v1.
This lead to issues when we changed the characters used later on.
We solved it by using Base64 to encode the shortened strings.

https://github.com/zws-im/zws/blob/0e41ad61ce523534b53aa8f9f7a5dd52fb9c29a9/src/services/urls.ts#L14-L16

This has several benefits to a custom encoding solution:
- Base64 is supported in all programming languages
- Base64 encoding implementations are usually optimized to be much faster than the naive encoding implementations

**Comment by aetheryx** [comment]
encode yourself some bitches

**Comment by vysiondev** [comment]
hey, first off thanks for offering this solution. I actually took a look at this same file, and couldn't *really* find the benefit of using base64 in this specific implemention. i'll try to explain why: although it's true that base64 has better support for all langauges, this implementation is specifically for golang, aka we don't need to bring other languages into the picture. second, i believe that your interpretation of how i encoded the strings are incorrect, as the [(scuffed) character index string](https://github.com/vysiondev/lolihost/blob/db8e6389cb294c19bbc2a8b070d366dec15f93b3/zws.go#L8) contains all the characters that are mapped to zero width unicode character tags. if i understand what you're suggesting correctly, it's that i should encode the file name to base64 first, then convert it to a zero-width string. if that's not the case/you wanted to clarify something then let me know

**Comment by pizzafox** [comment]
I misread the source originally. Converting a regular ID to zero-width characters like that is probably a bad idea but I can't think of a better way to do it.

**Comment by vysiondev** [comment]
if it aint broke dont fix it
